### ISSUE TITLE
Bootstrapping movim with Docker / Docker compose

### ISSUE THREAD

**Issue by sammcj** [movim/movim#226]
I was wondering if any thought had been given to simplify the install / bootstrapping of movim using [Docker Compose](https://docs.docker.com/compose/overview/) which is very simple and could standardise and simplify deployment on a larger scale?
- I am interested in the concept of movim.
- I have not yet tried movim.
- I do not have free time at present to set this up myself.

My thinking was, add a docker compose yaml file to the main source repo that sets up movim with sane defaults such as Alpine Linux or CentOS7 or Debian 8+Nginx+php-fpm+PostgreSQL (standard images / compose configs are already in abundance for this combination), deploy the code with some persistent storage volumes for data and fire away.

I really wish I had more time right now to do this for the community but it's _really_ bad timing resourcing time wise, so please don't think I'm just asking someone else to do this because I'm lazy.

I think that this could be a fantastic way to simplify the deployment of Movim and if that happened, traction would take place very quickly.

For example something like this:

``` yaml
version: '2'
services:
  nginx:
    build: ./docker/nginx-fpm
    image: schoren/nginx-fpm
    links:
      - phpfpm
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html

  phpfpm:
    build: ./docker/php56
    image: schoren/php56
    links:
      - pgsql

    volumes:
      - ./app:/var/www/html
      - ~/.composer:/var/www/.composer
      - ~/.ssh:/var/www/.ssh
    environment:
      PG_HOST: pgsql
      PG_DBNAME: app
      PG_USER: app
      PG_PASSWORD: 123

   pgsql:
     image: postgres
     volumes:
       - /var/lib/postgresql/data
     environment:
       POSTGRES_USER: app
       POSTGRES_DB: app
       POSTGRES_PASSWORD: 123
```

... then add in the app requirements from there.
