### ISSUE TITLE
No pending messages in muc anymore (mam:2)

### ISSUE THREAD

**Issue by srgcdev** [movim/movim#542]
Hello,

Since ejabberd was updated to 17.11, I can't receive pending messages in mucs anymore.
I think its related that now ejabberd supports mam:2.

Thanks in advance.

**Comment by mitchellurgero** [comment]
In the modules section of ejabberd.yml I am using 

```
    mod_muc:
        access: muc
        access_create: muc_create
        access_persistent: muc_create
        access_admin: muc_admin
        host: "muc.@HOST@"
    mod_mam: []
```

And this works as expected for me and public messages in mucs both external and internal.

In ejabberd.yml change ```loglevel: 3``` to ```loglevel: 5``` restart the service and see if you notice any errors or warnings.

I am also using ejabberd 17.11 (I however did a fresh install when upgrading and not a straight upgrade)
