### ISSUE TITLE
Code blocks have wrapped lines

### ISSUE THREAD

**Issue by phoe** [movim/movim#755]
Hey hi! I have a feature request.

https://nl.movim.eu/?blog/phoe%40movim.eu/3854edd0-e8fa-42eb-80fc-39eef3392c9f

You can see that the code blocks in here have wrapped lines. Is it possible to do one of the following instead?

1) change the CSS so there is horizontal scrolling instead
2) provide a wider layout for desktop browsers since there's a lot of white space. See https://i.imgtc.com/biJQWAv.png

**Comment by edhelas** [comment]
Horizontal scroll can be considered.
I'm not planning to widen the layout as it will affect the rest of the UI and makes text less readable.

**Comment by phoe** [comment]
If anyone wants to have a wider Movim on their device, here is a quickly hacked user style that allows this. It is not responsive and will therefore blow up at higher zooms.

```css
/* User style for movim.eu */

main > div {
    width: auto;
    max-width: 150rem; /* Edit this value to your liking */
}

main > div > * {
    max-width: none;
}
```
