### ISSUE TITLE
Can't connect to my ejabberd XMPP server

### ISSUE THREAD

**Issue by sbleblanc** [movim/movim#950]
Hey,

I installed Movim and configured it with MySql and nginx. I can get to the login page and admin page without problem. When I try to connect to my XMPP server, which is on the same box, it just hangs and reloads. On the daemon side, I only see this : 

```
Compiled hash file
Compiled po files
Movim daemon launched
Base URL: https://movim.sbl-dev.ca/

Debug is enabled, check the logs in syslog or /srv/www/movim/log/

--- Server Configuration - Apache ---
Enable the Secure WebSocket to WebSocket tunneling
# a2enmod proxy_wstunnel
Add this in your configuration file (default-ssl.conf)
ProxyPass /ws/ ws://127.0.0.1:12010/

--- Server Configuration - nginx ---
Add this in your configuration file
location /ws/ {
    proxy_pass http://127.0.0.1:12010/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_redirect off;
}

q4bkA3e1dfoTeRbk9i3aZucOcQeJ02pz : 506 connected
q4bkA3e1dfoTeRbk9i3aZucOcQeJ02pz : 568 internal connected
q4bkA3e1dfoTeRbk9i3aZucOcQeJ02pz : Picked STARTTLS
q4bkA3e1dfoTeRbk9i3aZucOcQeJ02pz : Connect to sbl-dev.ca:5222
q4bkA3e1dfoTeRbk9i3aZucOcQeJ02pz : Shutdown
q4bkA3e1dfoTeRbk9i3aZucOcQeJ02pz : Shutdown
q4bkA3e1dfoTeRbk9i3aZucOcQeJ02pz : linker killed
q4bkA3e1dfoTeRbk9i3aZucOcQeJ02pz : 506 deconnected
CFb1UJo1TQ4NjfGdXGqjBU4NS3ZPyYJE : 587 connected
CFb1UJo1TQ4NjfGdXGqjBU4NS3ZPyYJE : 600 internal connected
```

I can connect to my XMPP server using any other client. This is the related configuration :
```
[...]
listen:
  -
    port: 5222
    ip: "0.0.0.0"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: all
    starttls_required: true
    starttls: true
    dhfile: /opt/ejabberd/dh.pem
  -
    port: 5223
    ip: "0.0.0.0"
    module: ejabberd_c2s
    access: c2s
    shaper: c2s_shaper
    tls: true
    max_stanza_size: 65536
[...]
``` 
I am using the latest git version. I also tried the latest release, but got the same problem.

Am I missing an important configuration? If someone could help me it would be really apreciated, thank you!
