### ISSUE TITLE
Calls in Google Chrome

### ISSUE THREAD

**Issue by z814** [movim/movim#954]
Calls in Chrome don't work.
Error: Uncaught DOMException: Failed to construct 'RTCPeerConnection': 'stuns' is not one of the supported URL schemes 'stun', 'turn' or 'turns'.

**Comment by edhelas** [comment]
Hello, what kind of Movim version are you using. It seems that this was fixed a while ago already ?

**Comment by z814** [comment]
Movim v0.18.1rc8

**Comment by edhelas** [comment]
Can you please check your XMPP server STUN configuration. It seems that this "stuns" configuration is returned from XMPP.

**Comment by z814** [comment]
Yes! Ejabberd server is configured according to [instruction](https://www.process-one.net/blog/how-to-set-up-ejabberd-video-voice-calling/).

This config prevents Chrome from working.
```
host: example.com
port: 5349
type: stuns
transport: tcp
restricted: false
```

But in Firefox everything works with this config...

Thank you!

**Comment by edhelas** [comment]
type: stuns => type: stun // maybe ?

**Comment by z814** [comment]
I had a config as in the example from the link above:
```
modules:
  ...
  mod_stun_disco:
    credentials_lifetime: 12h
    services:
        -
          host: 0.0.0.0
          port: 3478
          type: stun
          transport: udp
          restricted: false
        -
          host: 0.0.0.0
          port: 3478
          type: turn
          transport: udp
          restricted: true
        -
          host: example.com
          port: 5349
          type: stuns
          transport: tcp
          restricted: false
        -
          host: example.com
          port: 5349
          type: turns
          transport: tcp
          restricted: true

```
Now I have removed the "stuns" section from it. The section with "stun" remained there.
